function str = sprintRoad(road)
%% 将道路的数据打印出来
if road.type == 1
  type = '小区内道路（1）';
elseif road.type == 2
  type = '小区周边道路（2）';
else
  error('invalid road type');
end
str =['道路数据     ', '道路类型：', type,...
      '  车道宽度：', num2str(road.width), '米',...
      '  道路长度：', num2str(road.length), '米',...
      '  车道数目：', num2str(road.nCarriageway), ...
      '  正常行驶速度:', num2str(road.v), '米/秒', ...
      '  交叉路口等待时间:', num2str(road.waitTime), '秒', ...
      '  通过无信号灯的交叉口时，减速到的最低速度:', num2str(road.vmin), '米/秒'];
end
